### ISSUE TITLE
Docker error : exec format error

### ISSUE THREAD

**Issue by matgenois** [benjefferies/gogo-garage-opener#4]
Hi!
I wanted to do this projet and saw yours so why not use it instead. So I've installed docker on my raspberry pi. I test that it works with this command : 
`docker run armhf/hello-world`
and it works great. 
Now I have build your project with the instructions you have mentionned. If I do docker images, here's the result : 
```
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
gogo-garage-opener-builder   latest              ef2e6b2124b2        30 minutes ago      674.6 MB
golang                       1.7                 7afbc2b03b9e        3 weeks ago         674.6 MB
hello-world                  latest              48b5124b2768        5 weeks ago         1.84 kB
armhf/hello-world            latest              d40384c3f861        5 months ago        1.636 kB
```
When I want to run the docker image, I get this error : 
```
$ docker run --rm -v "$PWD":/go/src/gogo-garage-opener -w /go/src/gogo-garage-opener gogo-garage-opener-builder:latest
exec format error
docker: Error response from daemon: Cannot start container dd4174ace6b5c628190bb919e7c01549b9990ff3f63152151740062ca06fe870: [9] System error: exec format error.
```

Seems like the image has not been build for the good architecture. Any idea how I could resume this?

Thank you!
Mathieu

**Comment by benjefferies** [comment]
Hi Mathieu

I'll try to reproduce this issue so I can get it fixed. As I understand you're trying to build the image on the raspberry pi. Which OS are you running on the raspberry pi? 

I haven't built the image on the raspberry pi yet. In the short term you might be able to work around this by building the binary on another machine and copying it to the raspberry pi. The following steps I have tested on 64 bit architecture on both mac os and linux (ubuntu).

1. `docker run --rm -v "$PWD":/go/src/gogo-garage-opener -w /go/src/gogo-garage-opener gogo-garage-opener-builder:latest`
1. Copy the output `gogo-garage-opener` binary file to the raspberry pi.
1. Run on raspberry pi `gogo-garage-opener -s 15 -r 18 -db /var/gogo-garage-opener/gogo-garage-opener.db`. (`-s should be set to the gpio for the magnetic switch, -r should be set to the gpio for the relay)

I will find some time this evening to look at building the binary on the raspberry pi.

Hope this helps.

Ben

**Comment by matgenois** [comment]
I have build it on Linux and tonight I'll copy the binary to my raspberry and try to run it!

**Comment by matgenois** [comment]
Hi Ben, I have copy the binary on the raspberry and looks like it works great!! Thank you for the precision!!

**Comment by benjefferies** [comment]
Great to hear Mathieu.

I have tried to clarify some of the details in the readme. If you spot anything that you think could be clarified feel free to raise a pull request 👍 

If you get anymore problems going forward or have any feedback it would be great to hear from you again.

As for now I think I will close this issue.
